export const SET_ALERT = "SET_ALERT";
export const REMOVE_ALERT = "REMOVE_ALERT";

export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";

export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";

export const USER_LOADED = "USER_LOADED";
export const AUTH_ERROR = "AUTH_ERROR";

export const LOGOUT = "LOGOUT";

export const CREATE_CATEGORY = "CREATE_CATEGORY";
export const GET_CATEGORIES = "GET_CATEGORIES";
export const CATEGORY_ERROR = "CATEGORY_ERROR";

export const ADD_PRODUCT = "ADD_PRODUCT";
export const GET_PRODUCT_BY_ARRIVAL = "GET_PRODUCT_BY_ARRIVAL";
export const GET_PRODUCT_BY_SELL = "GET_PRODUCT_BY_SELL";
export const GET_PRODUCT = "GET_PRODUCT";
export const RELATED_PRODUCTS = "RELATED_PRODUCTS";
export const PRODUCT_ERROR = "PRODUCT_ERROR";
